[package]
name = "inputs"
version = "0.1.0"
authors = ["Zack <zphixon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.2"
lazy_static = "*"
